// Package controlchannel provisions the RU→EU control channel: the pull.env
// file that carries the EU subscription host + shared token to the RU node so
// rdda-pull (config sync) and rdda-health (beat) can reach the EU controller.
//
// Both URLs are derived from a single sub host so the pull and health targets
// can never drift, and the whole file is generated instead of hand-written —
// the hand-written pull.env was one of the silent-failure traps in the field
// (G4): a missing or mistyped file left pull-sync and the health beat quietly
// off, and rdda-health.service failed outright on the absent EnvironmentFile.
package controlchannel

import (
	"fmt"
	"net/url"
	"strings"
)

// EnvFileName is the basename of the control-channel environment file inside the
// RDDA state dir. It is consumed as an EnvironmentFile by rdda-pull.service and
// rdda-health.service.
const EnvFileName = "pull.env"

// normalizeHost reduces a sub-host given as a bare hostname or a full URL
// ("https://sub.example.com/", "sub.example.com:443/ru") down to host[:port].
func normalizeHost(subHost string) string {
	h := strings.TrimSpace(subHost)
	if h == "" {
		return ""
	}
	if strings.Contains(h, "://") {
		if u, err := url.Parse(h); err == nil && u.Host != "" {
			return u.Host
		}
	}
	// Strip any path/query the operator may have pasted after the host.
	if i := strings.IndexAny(h, "/?"); i >= 0 {
		h = h[:i]
	}
	return strings.TrimSpace(h)
}

// RenderEnv builds the pull.env contents from the EU subscription hostname and
// the shared pull token. RDDA_PULL_FROM and RDDA_HEALTH_TO are both derived from
// subHost so the two endpoints stay in lock-step.
func RenderEnv(subHost, token string) (string, error) {
	host := normalizeHost(subHost)
	if host == "" {
		return "", fmt.Errorf("sub host is required (the EU Cloudflare sub hostname, e.g. sub.example.com)")
	}
	if strings.TrimSpace(token) == "" {
		return "", fmt.Errorf("pull token is required (the pull_token from the EU config.yaml)")
	}
	base := "https://" + host
	var b strings.Builder
	b.WriteString("# rdda control channel — generated by `rdda control-channel init`; do not hand-edit.\n")
	fmt.Fprintf(&b, "RDDA_PULL_FROM=%s/ru/config\n", base)
	fmt.Fprintf(&b, "RDDA_HEALTH_TO=%s/ru/health\n", base)
	fmt.Fprintf(&b, "RDDA_PULL_TOKEN=%s\n", strings.TrimSpace(token))
	return b.String(), nil
}
